apiVersion: v1
kind: Namespace
metadata:
  name: ronak

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
  namespace: ronak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
    spec:
      containers:
      - name: facebook
        image: ronak1907/simple-website-reactjs:59
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: facebook-svc
  namespace: ronak
spec:
  selector:
    app: facebook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
